name: Validate

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['22']

    name: Node v${{ matrix.node }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false

      - name: Checkout Master
        run: git branch -f master origin/master

      - name: Sanity Check
        run: |
          echo branch `git branch --show-current`;
          echo node `node --version`;
          echo yarn `pnpm --version`

      - name: Install Pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: true

      - name: Audit Dependencies
        run: pnpm security

      - name: Build Packages
        run: pnpm --recursive build

      - name: Lint Repo
        run: pnpm run lint

      - name: Run Tests
        run: pnpm ci:coverage
